### ISSUE TITLE
Draw

### ISSUE THREAD

**Issue by AFowke** [lucasmaystre/kickscore#1]
Is there a way to handle drawn matches? Thank you

**Comment by lucasmaystre** [comment]
Hi @AFowke, yes you can. Here's a small snippet.

    import kickscore as ks

    # `margin` defines the draw margin (higher = more draws)
    model = ks.TernaryModel(margin=0.5)

    model.add_item("a", kernel=ks.kernel.Constant(var=1.0))
    model.add_item("b", kernel=ks.kernel.Constant(var=2.0))

    # A wins over B at time t=0.0
    model.observe(winners=["a"], losers=["b"], tie=False, t=0.0)

    # A & B draw at time t=1.0
    model.observe(winners=["a"], losers=["b"], tie=True, t=1.0)

Let me know if it helps.
