### ISSUE TITLE
Delta updates

### ISSUE THREAD

**Issue by liampwll** [lucasmaystre/kickscore#3]
Is it possible to add observations to a model without having to fit the entire model again? I'd like to see how kickscore performs when it has observed all matches before a certain match for all matches in my dataset, but this is not feasible when I have to run `.fit` each time with 70000 matches.

**Comment by lucasmaystre** [comment]
Hi @liampwll you can definitely add observations after fitting a model. When you call `fit()` again, it doesn't start from scratch, but instead uses the score estimates from the previous call.

Here are some ideas on how to save time if you want to retrain & evaluate on many matches:

- you could limit the number of iterations to 1 or 2 per call `fit(max_iter=1)` after adding every match. (Every 100 matches or so, it would probably be good to let it run to convergence again, with a higher number of iterations)
- typically you don't need to retrain after _every_ match. I typically batch together matches that occurred on the same day.

This being said, I don't know the exact application you have in mind.

Also, if you're OK with slightly less accurate predictions, you can check out (TrueSkill)[https://trueskill.org/], which has constant-time updates.
