### ISSUE TITLE
Algorithm consideration

### ISSUE THREAD

**Issue by franz101** [lucasmaystre/kickscore#7]
Kickscore is a rating based model.
Over time a team might loose their rating but short term a longer break than the other team is considered a plus point.

How would you solve this mathematically

**Comment by amirbachar** [comment]
The way it can be modelled, is using two additional items:
1. decreasing the mean rating of the team linearly over time, and increasing it by a constant after each match to compensate for that.
2. Adding a positive feature "break from last match" or a negative feature "matches in the last 2 weeks", that will be added to a each team for that match (same as Home Field)

**Comment by lucasmaystre** [comment]
Agreed with @amirbachar - you can encode things like "momentum" with additional items.

**Comment by franz101** [comment]
Thank you, will try to test it in a few weeks. Also would love to improve the speed a bit of the Python module.

**Comment by victorkristof** [comment]
Hi @franz101, if speed is an issue for you, please note that we also have a [Go implementation of the Kickscore library](https://github.com/lucasmaystre/gokick), which makes computations more efficient. I hope this helps!
